Traceback (most recent call last):
  File "<string>", line 122, in <module>
  File "/Users/godishalarishi/anaconda3/lib/python3.11/site-packages/sklearn/ensemble/_forest.py", line 945, in predict_proba
    X = self._validate_X_predict(X)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/godishalarishi/anaconda3/lib/python3.11/site-packages/sklearn/ensemble/_forest.py", line 637, in _validate_X_predict
    X = validate_data(
        ^^^^^^^^^^^^^^
  File "/Users/godishalarishi/anaconda3/lib/python3.11/site-packages/sklearn/utils/validation.py", line 2929, in validate_data
    _check_feature_names(_estimator, X, reset=reset)
  File "/Users/godishalarishi/anaconda3/lib/python3.11/site-packages/sklearn/utils/validation.py", line 2787, in _check_feature_names
    raise ValueError(message)
ValueError: The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- cluster

Dataset shape: (111433, 11)
Sampled dataset shape: (50000, 11)
Selected features: ['table_contents', 'county', 'diameter', 'valuable_broadleaf_forest', 'all_age_classes', 'incl_formally_protected', 'unnamed6', 'table_contents_forest', 'lodgepole_pine_forest', 'year']
Optimal k: 4
Class distribution: tree_species
10-24                   37097
All diameter classes      991
25-                       989
0-9                       923
Name: count, dtype: int64
RF Accuracy: 0.9734
RF F1: 0.9756425546486346
RF ROC-AUC: 0.9968112008455275
Skipping XGB due to label issue.
